[workspace]
authors = ["chi1180 <143685104+chi1180@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "space_01"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
scipy = ">=1.10"
numpy = "<2"
pandas = "<2.2.0"
pycaret = "3.3.2"
tensorflow = ">=2.15"
